version: 2

android_config: &android_config
  working_directory: ~/code
  docker:
    - image: circleci/android:api-24
  environment:
    TERM: dumb
    JAVA_TOOL_OPTIONS: "-Xmx1024m"

jobs:
  build_and_test:
    <<: *android_config
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "device/build.gradle" }}-{{ checksum "domain/build.gradle" }}
      - run:
          name: Download secrets
          command: ./deploy_scripts/downloadUgandaSecrets.sh
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "device/build.gradle" }}-{{ checksum "domain/build.gradle" }}
      - run:
          name: Run Ethiopia linting
          command: ./gradlew lintEthiopiaRelease
      - run:
          name: Run Uganda linting
          command: ./gradlew lintUgandaRelease
      - run:
          name: Run unit tests for all flavours
          command: ./gradlew runUnitTests
      - store_artifacts:
          path: app/build/reports
          destination: reports/app
      - store_artifacts:
          path: device/build/reports
          destination: reports/device
      - store_artifacts:
          path: domain/build/reports
          destination: reports/domain
      - store_test_results:
          paths:
            - app/build/test-results
            - device/build/test-results
            - domain/build/test-results

  deploy_ethiopia_staging:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Deploy App to Play Store (Staging)
          command: |
            export VERSION_CODE=${CIRCLE_BUILD_NUM}
            ./deploy_scripts/downloadEthiopiaSecrets.sh
            ./gradlew assembleEthiopiaStaging
            ./gradlew publishEthiopiaStaging -Dorg.gradle.project.track=internal


  deploy_uganda_sandbox:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Deploy App to Play Store (Staging)
          command: |
            export VERSION_CODE=${CIRCLE_BUILD_NUM}
            ./deploy_scripts/downloadUgandaSecrets.sh
            ./gradlew assembleUgandaSandbox
            ./gradlew publishUgandaSandbox -Dorg.gradle.project.track=internal

  deploy_ethiopia_sandbox:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Deploy App to Play Store (Sandbox)
          command: |
            export VERSION_CODE=$((${CIRCLE_BUILD_NUM} + 240000000))
            ./deploy_scripts/downloadEthiopiaSecrets.sh
            ./gradlew assembleEthiopiaSandbox
            ./gradlew publishEthiopiaSandbox -Dorg.gradle.project.track=production

  deploy_demo:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Deploy App to Play Store (Demo)
          command: |
            export VERSION_CODE=${CIRCLE_BUILD_NUM}
            ./deploy_scripts/downloadEthiopiaSecrets.sh
            ./gradlew assembleEthiopiaDemo
            ./gradlew publishEthiopiaDemo -Dorg.gradle.project.track=production

  deploy_production_ethiopia:
    <<: *android_config
    steps:
      - checkout
      - run:
          name: Deploy App to Play Store (Production)
          command: |
            export VERSION_CODE=${CIRCLE_BUILD_NUM}
            ./deploy_scripts/downloadSecrets.sh
            ./gradlew assembleEthiopiaRelease
            ./gradlew publishEthiopiaRelease -Dorg.gradle.project.track=production

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy_ethiopia_staging:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
      - deploy_uganda_sandbox:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
              # ^ It is OK to deploy directly to Uganda sandbox when we push to master because
              # we do not need two separate test environments for Uganda.
      - deploy_ethiopia_sandbox:
          requires:
            - build_and_test
          filters:
            branches:
              only: sandbox
      - deploy_demo:
          requires:
            - build_and_test
          filters:
            branches:
              only: demo
      - deploy_production_ethiopia:
          requires:
            - build_and_test
          filters:
            branches:
              only: production-ethiopia
